###
POST http://localhost:8080/api/v1/auth/token
Content-Type: application/json

{
  "login": "user",
  "password": "1234"
}

###
POST http://localhost:8080/api/v1/auth/token
Content-Type: application/json

{
  "login": "admin",
  "password": "1234"
}

###
POST http://localhost:8080/api/v1/auth/token
Content-Type: application/json

{
  "login": "owner",
  "password": "1234"
}